/*
 Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function F(a){function c(){this.deflated||(a.widgets.focused==this.widget&&(this.focused=!0),a.widgets.destroy(this.widget),this.deflated=!0)}function f(){var d=a.editable(),b=a.document;if(this.deflated)this.widget=a.widgets.initOn(this.element,"image",this.widget.data),this.widget.inline&&!(new CKEDITOR.dom.elementPath(this.widget.wrapper,d)).block&&(d=b.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div"),d.replace(this.widget.wrapper),this.widget.wrapper.move(d)),this.focused&&
(this.widget.focus(),delete this.focused),delete this.deflated;else{var c=this.widget,d=e,b=c.wrapper,f=c.data.align,c=c.data.hasCaption;if(d){for(var m=3;m--;)b.removeClass(d[m]);"center"==f?c&&b.addClass(d[1]):"none"!=f&&b.addClass(d[r[f]])}else"center"==f?(c?b.setStyle("text-align","center"):b.removeStyle("text-align"),b.removeStyle("float")):("none"==f?b.removeStyle("float"):b.setStyle("float",f),b.removeStyle("text-align"))}}var e=a.config.image2_alignClasses,g=a.config.image2_captionedClass;
return{allowedContent:G(a),requiredContent:"img[src,alt]",features:H(a),styleableElements:"img figure",contentTransformations:[["img[width]: sizeToAttribute"]],editables:{caption:{selector:"figcaption",allowedContent:"br em strong sub sup u s; a[!href,target]"}},parts:{image:"img",caption:"figcaption"},dialog:"image2",template:'\x3cimg alt\x3d"" src\x3d"" /\x3e',data:function(){var d=this.features;this.data.hasCaption&&!a.filter.checkFeature(d.caption)&&(this.data.hasCaption=!1);"none"==this.data.align||
a.filter.checkFeature(d.align)||(this.data.align="none");this.shiftState({widget:this,element:this.element,oldData:this.oldData,newData:this.data,deflate:c,inflate:f});this.data.link?this.parts.link||(this.parts.link=this.parts.image.getParent()):this.parts.link&&delete this.parts.link;this.parts.image.setAttributes({src:this.data.src,"data-cke-saved-src":this.data.src,alt:this.data.alt});if(this.oldData&&!this.oldData.hasCaption&&this.data.hasCaption)for(var b in this.data.classes)this.parts.image.removeClass(b);
if(a.filter.checkFeature(d.dimension)){d=this.data;d={width:d.width,height:d.height};b=this.parts.image;for(var e in d)d[e]?b.setAttribute(e,d[e]):b.removeAttribute(e)}this.oldData=CKEDITOR.tools.extend({},this.data)},init:function(){var d=CKEDITOR.plugins.image2,b=this.parts.image,c={hasCaption:!!this.parts.caption,src:b.getAttribute("src"),alt:b.getAttribute("alt")||"",width:b.getAttribute("width")||"",height:b.getAttribute("height")||"",lock:this.ready?d.checkHasNaturalRatio(b):!0},f=b.getAscendant("a");
f&&this.wrapper.contains(f)&&(this.parts.link=f);c.align||(b=c.hasCaption?this.element:b,e?(b.hasClass(e[0])?c.align="left":b.hasClass(e[2])&&(c.align="right"),c.align?b.removeClass(e[r[c.align]]):c.align="none"):(c.align=b.getAttribute("align")||b.getStyle("float")||"none",b.removeStyle("float")));a.plugins.link&&this.parts.link&&(c.link=d.getLinkAttributesParser()(a,this.parts.link),(b=c.link.advanced)&&b.advCSSClasses&&(b.advCSSClasses=CKEDITOR.tools.trim(b.advCSSClasses.replace(/cke_\S+/,""))));
this.wrapper[(c.hasCaption?"remove":"add")+"Class"]("cke_image_nocaption");this.setData(c);a.filter.checkFeature(this.features.dimension)&&!0!==a.config.image2_disableResizer&&I(this);this.shiftState=d.stateShifter(this.editor);this.on("contextMenu",function(a){a.data.image=CKEDITOR.TRISTATE_OFF;if(this.parts.link||this.wrapper.getAscendant("a"))a.data.link=a.data.unlink=CKEDITOR.TRISTATE_OFF})},addClass:function(a){t(this).addClass(a)},hasClass:function(a){return t(this).hasClass(a)},removeClass:function(a){t(this).removeClass(a)},
getClasses:function(){var a=new RegExp("^("+[].concat(g,e).join("|")+")$");return function(){var c=this.repository.parseElementClasses(t(this).getAttribute("class")),e;for(e in c)a.test(e)&&delete c[e];return c}}(),upcast:J(a),downcast:K(a),getLabel:function(){return this.editor.lang.widget.label.replace(/%1/,(this.data.alt||"")+" "+this.pathName)}}}function J(a){var c=u(a),f=a.config.image2_captionedClass;return function(a,g){var d={width:1,height:1},b=a.name,h;if(!a.attributes["data-cke-realelement"]&&
(c(a)?("div"==b&&(h=a.getFirst("figure"))&&(a.replaceWith(h),a=h),g.align="center",h=a.getFirst("img")||a.getFirst("a").getFirst("img")):"figure"==b&&a.hasClass(f)?h=a.find(function(a){return"img"===a.name&&-1!==CKEDITOR.tools.array.indexOf(["figure","a"],a.parent.name)},!0)[0]:n(a)&&(h="a"==a.name?a.children[0]:a),h)){for(var D in d)(d=h.attributes[D])&&d.match(L)&&delete h.attributes[D];return a}}}function K(a){var c=a.config.image2_alignClasses;return function(a){var e="a"==a.name?a.getFirst():
a,g=e.attributes,d=this.data.align;if(!this.inline){var b=a.getFirst("span");b&&b.replaceWith(b.getFirst({img:1,a:1}))}d&&"none"!=d&&(b=CKEDITOR.tools.parseCssText(g.style||""),"center"==d&&"figure"==a.name?a=a.wrapWith(new CKEDITOR.htmlParser.element("div",c?{"class":c[1]}:{style:"text-align:center"})):d in{left:1,right:1}&&c&&e.addClass(c[r[d]]),c||CKEDITOR.tools.isEmpty(b)||(g.style=CKEDITOR.tools.writeCssText(b)),g.align=d);return a}}function u(a){var c=a.config.image2_captionedClass,f=a.config.image2_alignClasses,
e={figure:1,a:1,img:1};return function(g){if(!(g.name in{div:1,p:1}))return!1;var d=g.children;if(1!==d.length)return!1;d=d[0];if(!(d.name in e))return!1;if("p"==g.name){if(!n(d))return!1}else if("figure"==d.name){if(!d.hasClass(c))return!1}else if(a.enterMode==CKEDITOR.ENTER_P||!n(d))return!1;return(f?g.hasClass(f[1]):"center"==CKEDITOR.tools.parseCssText(g.attributes.style||"",!0)["text-align"])?!0:!1}}function n(a){return"img"==a.name?!0:"a"==a.name?1==a.children.length&&a.getFirst("img"):!1}function I(a){var c=
a.editor,f=c.editable(),e=c.document,g=a.resizer=e.createElement("span");g.addClass("cke_image_resizer");g.setAttribute("title",c.lang.image2.resizer);g.append(new CKEDITOR.dom.text("​",e));if(a.inline)a.wrapper.append(g);else{var d=a.parts.link||a.parts.image,b=d.getParent(),h=e.createElement("span");h.addClass("cke_image_resizer_wrapper");h.append(d);h.append(g);a.element.append(h,!0);b.is("span")&&b.remove()}g.on("mousedown",function(b){function d(a,c,b){var m=CKEDITOR.document,k=[];e.equals(m)||
k.push(m.on(a,c));k.push(e.on(a,c));if(b)for(a=k.length;a--;)b.push(k.pop())}function v(){w=r+l*z;x=Math.round(w/y)}function k(){x=u-p;w=Math.round(x*y)}var h=a.parts.image,B=function(){var a=c.config.image2_maxSize,b;if(!a)return null;a=CKEDITOR.tools.copy(a);b=CKEDITOR.plugins.image2.getNatural(h);a.width=Math.max("natural"===a.width?b.width:a.width,15);a.height=Math.max("natural"===a.height?b.height:a.height,15);return a}(),l="right"==a.data.align?-1:1,M=b.data.$.screenX,t=b.data.$.screenY,r=h.$.clientWidth,
u=h.$.clientHeight,y=r/u,n=[],E="cke_image_s"+(~l?"e":"w"),C,w,x,q,z,p,A;c.fire("saveSnapshot");d("mousemove",function(a){C=a.data.$;z=C.screenX-M;p=t-C.screenY;A=Math.abs(z/p);1==l?0>=z?0>=p?v():A>=y?v():k():0>=p?A>=y?k():v():k():0>=z?0>=p?A>=y?k():v():k():0>=p?v():A>=y?v():k();a=B&&(w>B.width||x>B.height);15>w||15>x||a||(q={width:w,height:x},h.setAttributes(q))},n);d("mouseup",function(){for(var b;b=n.pop();)b.removeListener();f.removeClass(E);g.removeClass("cke_image_resizing");if(q){a.setData(q);
b=a.data.src.split("/");var d=b[b.length-1];b=a.data.src.startsWith("/ImageLibrary")?a.data.src:"/"+b.slice(3).join("/");var m=a.data.src.substring(a.data.src.indexOf("/Content/UserFiles/Folders/")).replace("/Content/UserFiles/Folders/","").replace(d,"");"/"===m&&(m="");b=btoa(b)+"."+a.data.src.split(".").pop();var k=new Image;k.src="/ImageLibrary/Content/UserFiles/Backups/"+b;k.onload=function(){var b=document.createElement("canvas");b.width=q.width;b.height=q.height;var k=b.getContext("2d");k.drawImage(this,
0,0,this.width,this.height,0,0,b.width,b.height);k.canvas.toBlob(function(b){b=new File([b],d,{type:b.type,lastModified:Date.now()});b=c.uploadRepository.create(b);b.on("uploaded",function(b){c.fire("saveSnapshot");q=!1;a.init()});b.loadAndUpload(c.config.resizingUploadUrl,{path:m})})}}},n);f.addClass(E);g.addClass("cke_image_resizing")});a.on("data",function(){g["right"==a.data.align?"addClass":"removeClass"]("cke_image_resizer_left")})}function N(a){var c=[],f;return function(e){var g=a.getCommand("justify"+
e);if(g){c.push(function(){g.refresh(a,a.elementPath())});if(e in{right:1,left:1,center:1})g.on("exec",function(d){var b=l(a);if(b){b.setData("align",e);for(b=c.length;b--;)c[b]();d.cancel()}});g.on("refresh",function(c){var b=l(a),g={right:1,left:1,center:1};b&&(void 0===f&&(f=a.filter.checkFeature(a.widgets.registered.image.features.align)),f?this.setState(b.data.align==e?CKEDITOR.TRISTATE_ON:e in g?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED):this.setState(CKEDITOR.TRISTATE_DISABLED),c.cancel())})}}}
function O(a){if(a.plugins.link){var c=CKEDITOR.on("dialogDefinition",function(c){c=c.data;if("link"==c.name){c=c.definition;var e=c.onShow,g=c.onOk;c.onShow=function(){var c=l(a),b=this.getContentElement("info","linkDisplayText").getElement().getParent().getParent();c&&(c.inline?!c.wrapper.getAscendant("a"):1)?(this.setupContent(c.data.link||{}),b.hide()):(b.show(),e.apply(this,arguments))};c.onOk=function(){var c=l(a);if(c&&(c.inline?!c.wrapper.getAscendant("a"):1)){var b={};this.commitContent(b);
c.setData("link",b)}else g.apply(this,arguments)}}});a.on("destroy",function(){c.removeListener()});a.getCommand("unlink").on("exec",function(c){var e=l(a);e&&e.parts.link&&(e.setData("link",null),this.refresh(a,a.elementPath()),c.cancel())});a.getCommand("unlink").on("refresh",function(c){var e=l(a);e&&(this.setState(e.data.link||e.wrapper.getAscendant("a")?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED),c.cancel())})}}function l(a){return(a=a.widgets.focused)&&"image"==a.name?a:null}function G(a){var c=
a.config.image2_alignClasses;a={div:{match:u(a)},p:{match:u(a)},img:{attributes:"!src,alt,width,height,align"},figure:{classes:"!"+a.config.image2_captionedClass},figcaption:!0};c?(a.div.classes=c[1],a.p.classes=a.div.classes,a.img.classes=c[0]+","+c[2],a.figure.classes+=","+a.img.classes):(a.div.styles="text-align",a.p.styles="text-align",a.img.styles="float",a.figure.styles="float,display");return a}function H(a){a=a.config.image2_alignClasses;return{dimension:{requiredContent:"img[width,height]"},
align:{requiredContent:"img"+(a?"("+a[0]+")":"{float}")},caption:{requiredContent:"figcaption"}}}function t(a){return a.data.hasCaption?a.element:a.parts.image}var P=new CKEDITOR.template('\x3cfigure class\x3d"{captionedClass}"\x3e\x3cimg alt\x3d"" src\x3d"" /\x3e\x3cfigcaption\x3e{captionPlaceholder}\x3c/figcaption\x3e\x3c/figure\x3e'),r={left:0,center:1,right:2},L=/^\s*(\d+\%)\s*$/i;CKEDITOR.plugins.add("image2",{lang:"af,ar,az,bg,bn,bs,ca,cs,cy,da,de,de-ch,el,en,en-au,en-ca,en-gb,eo,es,es-mx,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,oc,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn",
requires:"widget,dialog",icons:"image",hidpi:!0,onLoad:function(){CKEDITOR.addCss('.cke_image_nocaption{line-height:0}.cke_editable.cke_image_sw, .cke_editable.cke_image_sw *{cursor:sw-resize !important}.cke_editable.cke_image_se, .cke_editable.cke_image_se *{cursor:se-resize !important}.cke_image_resizer{display:none;position:absolute;width:10px;height:10px;bottom:-5px;right:-5px;background:#000;outline:1px solid #fff;line-height:0;cursor:se-resize;}.cke_image_resizer_wrapper{position:relative;display:inline-block;line-height:0;}.cke_image_resizer.cke_image_resizer_left{right:auto;left:-5px;cursor:sw-resize;}.cke_widget_wrapper:hover .cke_image_resizer,.cke_image_resizer.cke_image_resizing{display:block}.cke_editable[contenteditable\x3d"false"] .cke_image_resizer{display:none;}.cke_widget_wrapper\x3ea{display:inline-block}')},
init:function(a){if(!a.plugins.detectConflict("image2",["easyimage"])){var c=a.config,f=a.lang.image2,e=F(a);c.filebrowserImage2BrowseUrl=c.filebrowserImageBrowseUrl;c.filebrowserImage2UploadUrl=c.filebrowserImageUploadUrl;e.pathName=f.pathName;e.editables.caption.pathName=f.pathNameCaption;a.widgets.add("image",e);a.ui.addButton&&a.ui.addButton("Image",{label:a.lang.common.image,command:"image",toolbar:"insert,10"});a.contextMenu&&(a.addMenuGroup("image",10),a.addMenuItem("image",{label:f.menu,command:"image",
group:"image"}));CKEDITOR.dialog.add("image2",this.path+"dialogs/image2.js")}},afterInit:function(a){var c={left:1,right:1,center:1,block:1},f=N(a),e;for(e in c)f(e);O(a)}});CKEDITOR.plugins.image2={stateShifter:function(a){function c(a,c){var b={};g?b.attributes={"class":g[1]}:b.styles={"text-align":"center"};b=e.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div",b);f(b,c);c.move(b);return b}function f(c,d){if(d.getParent()){var e=a.createRange();e.moveToPosition(d,CKEDITOR.POSITION_BEFORE_START);
d.remove();b.insertElementIntoRange(c,e)}else c.replace(d)}var e=a.document,g=a.config.image2_alignClasses,d=a.config.image2_captionedClass,b=a.editable(),h=["hasCaption","align","link"],l={align:function(b,d,e){var f=b.element;b.changed.align?b.newData.hasCaption||("center"==e&&(b.deflate(),b.element=c(a,f)),b.changed.hasCaption||"center"!=d||"center"==e||(b.deflate(),d=f.findOne("a,img"),d.replace(f),b.element=d)):"center"==e&&b.changed.hasCaption&&!b.newData.hasCaption&&(b.deflate(),b.element=
c(a,f));!g&&f.is("figure")&&("center"==e?f.setStyle("display","inline-block"):f.removeStyle("display"))},hasCaption:function(b,c,k){b.changed.hasCaption&&(c=b.element.is({img:1,a:1})?b.element:b.element.findOne("a,img"),b.deflate(),k?(k=CKEDITOR.dom.element.createFromHtml(P.output({captionedClass:d,captionPlaceholder:a.lang.image2.captionPlaceholder}),e),f(k,b.element),c.replace(k.findOne("img")),b.element=k):(c.replace(b.element),b.element=c))},link:function(b,c,d){if(b.changed.link){var f=b.element.is("img")?
b.element:b.element.findOne("img"),g=b.element.is("a")?b.element:b.element.findOne("a"),h=b.element.is("a")&&!d||b.element.is("img")&&d,l;h&&b.deflate();d?(c||(l=e.createElement("a",{attributes:{href:b.newData.link.url}}),l.replace(f),f.move(l)),d=CKEDITOR.plugins.image2.getLinkAttributesGetter()(a,d),CKEDITOR.tools.isEmpty(d.set)||(l||g).setAttributes(d.set),d.removed.length&&(l||g).removeAttributes(d.removed)):(d=g.findOne("img"),d.replace(g),l=d);h&&(b.element=l)}}};return function(a){var b,c;
a.changed={};for(c=0;c<h.length;c++)b=h[c],a.changed[b]=a.oldData?a.oldData[b]!==a.newData[b]:!1;for(c=0;c<h.length;c++)b=h[c],l[b](a,a.oldData?a.oldData[b]:null,a.newData[b]);a.inflate()}},checkHasNaturalRatio:function(a){var c=a.$;a=this.getNatural(a);return Math.round(c.clientWidth/a.width*a.height)==c.clientHeight||Math.round(c.clientHeight/a.height*a.width)==c.clientWidth},getNatural:function(a){if(a.$.naturalWidth)a={width:a.$.naturalWidth,height:a.$.naturalHeight};else{var c=new Image;c.src=
a.getAttribute("src");a={width:c.width,height:c.height}}return a},getLinkAttributesGetter:function(){return CKEDITOR.plugins.link.getLinkAttributes},getLinkAttributesParser:function(){return CKEDITOR.plugins.link.parseLinkAttributes}}})();CKEDITOR.config.image2_captionedClass="image";