/*
 Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.dialog.add("image2",function(e){function D(){var a=this.getValue().match(E);(a=!(!a||0===parseInt(a[1],10)))||alert(c.invalidLength.replace("%1",c[this.id]).replace("%2","px"));return a}function O(){function a(a,d){f.push(b.once(a,function(a){for(var b;b=f.pop();)b.removeListener();d(a)}))}var b=t.createElement("img"),f=[];return function(f,d,e){a("load",function(){var a=F(b);d.call(e,b,a.width,a.height)});a("error",function(){d(null)});a("abort",function(){d(null)});b.setAttribute("src",
(x.baseHref||"")+f+"?"+Math.random().toString(16).substring(2))}}function G(){var a=this.getValue();u(!1);a!==y.data.src?(H(a,function(a,f,b){u(!0);if(!a)return p(!1);if(e.getSelection()){for(var d=e.getSelection().getStartElement(),c="DIV TD P SECTION TBODY UL LI BODY HTML".split(" ");d.$&&!(0<=c.findIndex(function(a){return a===d.$.tagName.toUpperCase()}));)d=d.getParent();d&&d.getSize("width")&&(c=parseInt(d.getSize("width")),b=parseInt(c*b/f),f=c)}k.setValue(!1===e.config.image2_prefillDimensions?
0:f);l.setValue(!1===e.config.image2_prefillDimensions?0:b);v=m=f;w=n=b;p(I.checkHasNaturalRatio(a))}),q=!0):q?(u(!0),k.setValue(m),l.setValue(n),q=!1):u(!0)}function J(){if(g){var a=this.getValue();if(a&&(a.match(E)||p(!1),"0"!==a)){var b="width"==this.id,f=m||v,c=n||w,a=b?Math.round(a/f*c):Math.round(a/c*f);isNaN(a)||(b?l:k).setValue(a)}}}function p(a){if(h){if("boolean"==typeof a){if(z)return;g=a}else a=k.getValue(),z=!0,(g=!g)&&a&&(a*=n/m,isNaN(a)||l.setValue(Math.round(a)));h[g?"removeClass":
"addClass"]("cke_btn_unlocked");h.setAttribute("aria-checked",g);CKEDITOR.env.hc&&h.getChild(0).setHtml(g?CKEDITOR.env.ie?"■":"▣":CKEDITOR.env.ie?"□":"▢")}}function u(a){a=a?"enable":"disable";k[a]();l[a]()}var E=/(^\s*(\d+)(px)?\s*$)|^$/i,K=CKEDITOR.tools.getNextId(),L=CKEDITOR.tools.getNextId(),b=e.lang.image2,c=e.lang.common,P=(new CKEDITOR.template('\x3cdiv\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.lockRatio+'" class\x3d"cke_btn_locked" id\x3d"{lockButtonId}" role\x3d"checkbox"\x3e\x3cspan class\x3d"cke_icon"\x3e\x3c/span\x3e\x3cspan class\x3d"cke_label"\x3e'+
b.lockRatio+'\x3c/span\x3e\x3c/a\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.resetSize+'" class\x3d"cke_btn_reset" id\x3d"{resetButtonId}" role\x3d"button"\x3e\x3cspan class\x3d"cke_label"\x3e'+b.resetSize+"\x3c/span\x3e\x3c/a\x3e\x3c/div\x3e")).output({lockButtonId:K,resetButtonId:L}),I=CKEDITOR.plugins.image2,x=e.config,A=!(!x.filebrowserImageBrowseUrl&&!x.filebrowserBrowseUrl),B=e.widgets.registered.image.features,F=I.getNatural,t,y,M,H,m,n,v,w,q,g,z,h,r,k,l,C,N=[{id:"src",
type:"text",label:c.url,onKeyup:G,onChange:G,setup:function(a){this.setValue(a.data.src)},commit:function(a){a.setData("src",this.getValue())},validate:CKEDITOR.dialog.validate.notEmpty(b.urlMissing)}];A&&N.push({type:"button",id:"browse",style:"display:inline-block;margin-top:14px;",align:"center",label:e.lang.common.browseServer,hidden:!0,filebrowser:"info:src"});return{title:b.title,minWidth:250,minHeight:100,onLoad:function(){t=this._.element.getDocument();H=O()},onShow:function(){y=this.getModel();
M=y.parts.image;q=z=g=!1;C=F(M);v=m=C.width;w=n=C.height},contents:[{id:"info",label:b.infoTab,elements:[{type:"vbox",padding:0,children:[{type:"hbox",widths:["100%"],className:"cke_dialog_image_url",children:N}]},{id:"alt",type:"text",label:b.alt,setup:function(a){this.setValue(a.data.alt)},commit:function(a){a.setData("alt",this.getValue())},validate:!0===e.config.image2_altRequired?CKEDITOR.dialog.validate.notEmpty(b.altMissing):null},{type:"hbox",widths:["25%","25%","50%"],requiredContent:B.dimension.requiredContent,
children:[{type:"text",width:"45px",id:"width",label:c.width,validate:D,onKeyUp:J,onLoad:function(){k=this},setup:function(a){this.setValue(a.data.width)},commit:function(a){a.setData("width",this.getValue())}},{type:"text",id:"height",width:"45px",label:c.height,validate:D,onKeyUp:J,onLoad:function(){l=this},setup:function(a){this.setValue(a.data.height)},commit:function(a){a.setData("height",this.getValue())}},{id:"lock",type:"html",style:"margin-top:18px;width:40px;height:20px;",onLoad:function(){function a(a){a.on("mouseover",
function(){this.addClass("cke_btn_over")},a);a.on("mouseout",function(){this.removeClass("cke_btn_over")},a)}var b=this.getDialog();h=t.getById(K);r=t.getById(L);h&&(b.addFocusable(h,4+A),h.on("click",function(a){p();a.data&&a.data.preventDefault()},this.getDialog()),a(h));r&&(b.addFocusable(r,5+A),r.on("click",function(a){q?(k.setValue(v),l.setValue(w)):(k.setValue(m),l.setValue(n));a.data&&a.data.preventDefault()},this),a(r))},setup:function(a){p(a.data.lock)},commit:function(a){a.setData("lock",
g)},html:P}]},{type:"hbox",id:"alignment",requiredContent:B.align.requiredContent,children:[{id:"align",type:"radio",items:[[c.alignNone,"none"],[c.left,"left"],[c.center,"center"],[c.right,"right"]],label:c.align,setup:function(a){this.setValue(a.data.align)},commit:function(a){a.setData("align",this.getValue())}}]},{id:"hasCaption",type:"checkbox",label:b.captioned,requiredContent:B.caption.requiredContent,setup:function(a){this.setValue(a.data.hasCaption)},commit:function(a){a.setData("hasCaption",
this.getValue())}}]},{id:"Upload",hidden:!0,filebrowser:"uploadButton",label:b.uploadTab,elements:[{type:"file",id:"upload",label:b.btnUpload,style:"height:40px"},{type:"fileButton",id:"uploadButton",filebrowser:"info:src",label:b.btnUpload,"for":["Upload","upload"]}]}]}});