/*
 Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.dialog.add("image2",function(d){function D(){var a=this.getValue().match(E);(a=!(!a||0===parseInt(a[1],10)))||alert(g.invalidLength.replace("%1",g[this.id]).replace("%2","px"));return a}function O(){function a(a,d){b.push(e.once(a,function(a){for(var e;e=b.pop();)e.removeListener();d(a)}))}var e=t.createElement("img"),b=[];return function(b,d,c){a("load",function(){var a=F(e);d.call(c,e,a.width,a.height)});a("error",function(){d(null)});a("abort",function(){d(null)});e.setAttribute("src",
(x.baseHref||"")+b+"?"+Math.random().toString(16).substring(2))}}function G(){var a=this.getValue();u(!1);a!==y.data.src?(H(a,function(a,b,c){u(!0);if(!a)return p(!1);k.setValue(!1===d.config.image2_prefillDimensions?0:b);l.setValue(!1===d.config.image2_prefillDimensions?0:c);v=m=b;w=n=c;p(I.checkHasNaturalRatio(a))}),q=!0):q?(u(!0),k.setValue(m),l.setValue(n),q=!1):u(!0)}function J(){if(f){var a=this.getValue();if(a&&(a.match(E)||p(!1),"0"!==a)){var e="width"==this.id,b=m||v,d=n||w,a=e?Math.round(a/
b*d):Math.round(a/d*b);isNaN(a)||(e?l:k).setValue(a)}}}function p(a){if(h){if("boolean"==typeof a){if(z)return;f=a}else a=k.getValue(),z=!0,(f=!f)&&a&&(a*=n/m,isNaN(a)||l.setValue(Math.round(a)));h[f?"removeClass":"addClass"]("cke_btn_unlocked");h.setAttribute("aria-checked",f);CKEDITOR.env.hc&&h.getChild(0).setHtml(f?CKEDITOR.env.ie?"■":"▣":CKEDITOR.env.ie?"□":"▢")}}function u(a){a=a?"enable":"disable";k[a]();l[a]()}var E=/(^\s*(\d+)(px)?\s*$)|^$/i,K=CKEDITOR.tools.getNextId(),L=CKEDITOR.tools.getNextId(),
c=d.lang.image2,g=d.lang.common,P=(new CKEDITOR.template('\x3cdiv\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+c.lockRatio+'" class\x3d"cke_btn_locked" id\x3d"{lockButtonId}" role\x3d"checkbox"\x3e\x3cspan class\x3d"cke_icon"\x3e\x3c/span\x3e\x3cspan class\x3d"cke_label"\x3e'+c.lockRatio+'\x3c/span\x3e\x3c/a\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+c.resetSize+'" class\x3d"cke_btn_reset" id\x3d"{resetButtonId}" role\x3d"button"\x3e\x3cspan class\x3d"cke_label"\x3e'+
c.resetSize+"\x3c/span\x3e\x3c/a\x3e\x3c/div\x3e")).output({lockButtonId:K,resetButtonId:L}),I=CKEDITOR.plugins.image2,x=d.config,A=!(!x.filebrowserImageBrowseUrl&&!x.filebrowserBrowseUrl),B=d.widgets.registered.image.features,F=I.getNatural,t,y,M,H,m,n,v,w,q,f,z,h,r,k,l,C,N=[{id:"src",type:"text",label:g.url,onKeyup:G,onChange:G,setup:function(a){this.setValue(a.data.src)},commit:function(a){if(d.getSelection()){for(var e=d.getSelection().getStartElement(),b="DIV TD P SECTION TBODY UL LI BODY HTML".split(" ");e.$&&
!(0<=b.findIndex(function(a){return a===e.$.tagName.toUpperCase()}));)e=e.getParent();if(e&&e.getSize("width")){var c=this.getValue(),b=c.split("/"),g=b[b.length-1],b=c.startsWith("/ImageLibrary")?c:"/"+b.slice(3).join("/"),b=btoa(b)+"."+c.split(".").pop(),f=new Image;f.src="/ImageLibrary/Content/UserFiles/Backups/"+b;f.onload=function(){var b=document.createElement("canvas");b.width=e.getSize("width");b.height=b.width*f.height/f.width;a.setData("width",b.width);a.setData("height",b.height);var h=
b.getContext("2d");h.drawImage(f,0,0,f.width,f.height,0,0,b.width,b.height);h.canvas.toBlob(function(b){b=new File([b],g,{type:b.type,lastModified:Date.now()});b=d.uploadRepository.create(b);b.on("uploaded",function(){d.fire("saveSnapshot");a.setData("src",c)});var e=c.substring(c.indexOf("/Content/UserFiles/Folders/")).replace("/Content/UserFiles/Folders/","").replace(g,"");"/"===e&&(e="");b.loadAndUpload(d.config.resizingUploadUrl,{path:e})})}}}else a.setData("src",this.getValue())},validate:CKEDITOR.dialog.validate.notEmpty(c.urlMissing)}];
A&&N.push({type:"button",id:"browse",style:"display:inline-block;margin-top:14px;",align:"center",label:d.lang.common.browseServer,hidden:!0,filebrowser:"info:src"});return{title:c.title,minWidth:250,minHeight:100,onLoad:function(){t=this._.element.getDocument();H=O()},onShow:function(){y=this.getModel();M=y.parts.image;q=z=f=!1;C=F(M);v=m=C.width;w=n=C.height},contents:[{id:"info",label:c.infoTab,elements:[{type:"vbox",padding:0,children:[{type:"hbox",widths:["100%"],className:"cke_dialog_image_url",
children:N}]},{id:"alt",type:"text",label:c.alt,setup:function(a){this.setValue(a.data.alt)},commit:function(a){a.setData("alt",this.getValue())},validate:!0===d.config.image2_altRequired?CKEDITOR.dialog.validate.notEmpty(c.altMissing):null},{type:"hbox",widths:["25%","25%","50%"],requiredContent:B.dimension.requiredContent,children:[{type:"text",width:"45px",id:"width",label:g.width,validate:D,onKeyUp:J,onLoad:function(){k=this},setup:function(a){this.setValue(a.data.width)},commit:function(a){a.setData("width",
this.getValue())}},{type:"text",id:"height",width:"45px",label:g.height,validate:D,onKeyUp:J,onLoad:function(){l=this},setup:function(a){this.setValue(a.data.height)},commit:function(a){a.setData("height",this.getValue())}},{id:"lock",type:"html",style:"margin-top:18px;width:40px;height:20px;",onLoad:function(){function a(a){a.on("mouseover",function(){this.addClass("cke_btn_over")},a);a.on("mouseout",function(){this.removeClass("cke_btn_over")},a)}var c=this.getDialog();h=t.getById(K);r=t.getById(L);
h&&(c.addFocusable(h,4+A),h.on("click",function(a){p();a.data&&a.data.preventDefault()},this.getDialog()),a(h));r&&(c.addFocusable(r,5+A),r.on("click",function(a){q?(k.setValue(v),l.setValue(w)):(k.setValue(m),l.setValue(n));a.data&&a.data.preventDefault()},this),a(r))},setup:function(a){p(a.data.lock)},commit:function(a){a.setData("lock",f)},html:P}]},{type:"hbox",id:"alignment",requiredContent:B.align.requiredContent,children:[{id:"align",type:"radio",items:[[g.alignNone,"none"],[g.left,"left"],
[g.center,"center"],[g.right,"right"]],label:g.align,setup:function(a){this.setValue(a.data.align)},commit:function(a){a.setData("align",this.getValue())}}]},{id:"hasCaption",type:"checkbox",label:c.captioned,requiredContent:B.caption.requiredContent,setup:function(a){this.setValue(a.data.hasCaption)},commit:function(a){a.setData("hasCaption",this.getValue())}}]},{id:"Upload",hidden:!0,filebrowser:"uploadButton",label:c.uploadTab,elements:[{type:"file",id:"upload",label:c.btnUpload,style:"height:40px"},
{type:"fileButton",id:"uploadButton",filebrowser:"info:src",label:c.btnUpload,"for":["Upload","upload"]}]}]}});